[Security] [BEL-5828] Faraday usage updated and packages upgrades
belvo-finance/belvo-ruby pull request #121
Opened 2022-05-02 10:08 UTC by AlbertMaristany

:question: What
---

- [Update Faraday usage](https://lostisland.github.io/faraday/middleware/authentication) to avoid the deprecation warnings
- Update packages with security updates

:speech_balloon: Why
---
- Ruby gem up to date with latest security fixes

2022-05-04 22:12 UTC, Janee requested changes
I can't run the test, did you tried?

Here is my response:
```ruby
bundle exec rspec
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.

An error occurred while loading spec_helper.
Failure/Error: Coveralls.wear!

RuntimeError:
  coverage measurement is already setup
# ./spec/spec_helper.rb:12:in `<top (required)>'
No examples found.
No examples found.


Finished in 0.00003 seconds (files took 1.1 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

Finished in 0.00003 seconds (files took 1.1 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples


[Coveralls] Outside the CI environment, not sending data.
Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected
```

2022-05-05 07:25 UTC, AlbertMaristany commented
@Janee yes! Runs well on my side.

```ruby
bundle exec rake spec
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.

Belvo::Account
  can create accounts
  can get an account detail
  can filter when listing

Belvo::Balance
  can create
  can change options when creating

Belvo::Client
  raises error when no url given
  raises error when wrong credentials
  can login when credentials are correct
  given an environment the session should have the correct API URL
  given an environment the session should have the correct API URL
  given an environment the session should have the correct API URL
  given an URL the session should have the same one

Environment
  given an environment name should return a valid API URL
  given an environment name should return a valid API URL
  given an environment name should return a valid API URL
  given an URL should return the same one as default

Belvo::Income
  can create
  can change options when creating

Belvo::Institution
  can list

Belvo::InvestmentsPortfolio
  can create
  can change options when creating

Belvo::InvestmentsTransaction
  can create
  can change options when creating

Belvo::Invoice
  can create
  can change options when creating
  can list invoices with pagination

Belvo::Link
  can list links
  can create a link
  can create a recurrent link
  can create a link with username_type
  can create a link with two usernames
  can create a link with three usernames
  can create a link with two passwords
  can create a link with certificate and private_key
  can update an existing link
  can create a new link token
  can create a link with an external_id
  can patch a link with access_mode

Belvo::Owner
  can create
  can change options when creating

Belvo::RecurringExpenses
  can create
  can change options when creating

Belvo::RiskInsights
  can create
  can change options when creating

Belvo::Statement
  can create
  can change options when creating

Belvo::TaxComplianceStatus
  can create
  can change options when creating

Belvo::TaxReturn
  can create
  can change options when creating
  can create with dates

Belvo::TaxStatus
  can create
  can change options when creating

Belvo::Transaction
  can create transactions
  can change transaction options when creating

Utils
  read_file_to_b64 returns nil with bad file
  read_file_to_b64 works with good file

Belvo::WidgetToken
  can create a new token
  can create a new token with link_id and scopes
  can create a new token with link_id and scopes and widget branding

Belvo
  Version
    has a version number
  Belvo::Client
    has a links attribute
    has an accounts attribute
    has a transactions attribute
    has an owners attribute
    has a balances attribute
    has a statements attribute
    has an incomes attribute
    has an invoices attribute
    has a recurring_expenses attribute
    has a risk_insights attribute
    has a tax_returns attribute
    has a tax_status attribute
    has an institutions attribute
    has an widget_token attribute
    has an investments_portfolio attribute
    has an investments_transaction attribute

Finished in 0.12699 seconds (files took 0.56697 seconds to load)
77 examples, 0 failures

[Coveralls] Outside the CI environment, not sending data.

```

It might be the missing `rake` in your command?

2022-05-05 17:03 UTC, Janee commented
> @Janee yes! Runs well on my side.
> 
> ```ruby
> bundle exec rake spec
> [Coveralls] Set up the SimpleCov formatter.
> [Coveralls] Using SimpleCov's default settings.
> 
> Belvo::Account
>   can create accounts
>   can get an account detail
>   can filter when listing
> 
> Belvo::Balance
>   can create
>   can change options when creating
> 
> Belvo::Client
>   raises error when no url given
>   raises error when wrong credentials
>   can login when credentials are correct
>   given an environment the session should have the correct API URL
>   given an environment the session should have the correct API URL
>   given an environment the session should have the correct API URL
>   given an URL the session should have the same one
> 
> Environment
>   given an environment name should return a valid API URL
>   given an environment name should return a valid API URL
>   given an environment name should return a valid API URL
>   given an URL should return the same one as default
> 
> Belvo::Income
>   can create
>   can change options when creating
> 
> Belvo::Institution
>   can list
> 
> Belvo::InvestmentsPortfolio
>   can create
>   can change options when creating
> 
> Belvo::InvestmentsTransaction
>   can create
>   can change options when creating
> 
> Belvo::Invoice
>   can create
>   can change options when creating
>   can list invoices with pagination
> 
> Belvo::Link
>   can list links
>   can create a link
>   can create a recurrent link
>   can create a link with username_type
>   can create a link with two usernames
>   can create a link with three usernames
>   can create a link with two passwords
>   can create a link with certificate and private_key
>   can update an existing link
>   can create a new link token
>   can create a link with an external_id
>   can patch a link with access_mode
> 
> Belvo::Owner
>   can create
>   can change options when creating
> 
> Belvo::RecurringExpenses
>   can create
>   can change options when creating
> 
> Belvo::RiskInsights
>   can create
>   can change options when creating
> 
> Belvo::Statement
>   can create
>   can change options when creating
> 
> Belvo::TaxComplianceStatus
>   can create
>   can change options when creating
> 
> Belvo::TaxReturn
>   can create
>   can change options when creating
>   can create with dates
> 
> Belvo::TaxStatus
>   can create
>   can change options when creating
> 
> Belvo::Transaction
>   can create transactions
>   can change transaction options when creating
> 
> Utils
>   read_file_to_b64 returns nil with bad file
>   read_file_to_b64 works with good file
> 
> Belvo::WidgetToken
>   can create a new token
>   can create a new token with link_id and scopes
>   can create a new token with link_id and scopes and widget branding
> 
> Belvo
>   Version
>     has a version number
>   Belvo::Client
>     has a links attribute
>     has an accounts attribute
>     has a transactions attribute
>     has an owners attribute
>     has a balances attribute
>     has a statements attribute
>     has an incomes attribute
>     has an invoices attribute
>     has a recurring_expenses attribute
>     has a risk_insights attribute
>     has a tax_returns attribute
>     has a tax_status attribute
>     has an institutions attribute
>     has an widget_token attribute
>     has an investments_portfolio attribute
>     has an investments_transaction attribute
> 
> Finished in 0.12699 seconds (files took 0.56697 seconds to load)
> 77 examples, 0 failures
> 
> [Coveralls] Outside the CI environment, not sending data.
> ```
> 
> It might be the missing `rake` in your command?

Seems to be related with my laptop (changed the machine a last week) 🙃 
If you can run the test, then I'm ok with this :)

2022-05-05 17:03 UTC, Janee approved these changes

2022-05-06 07:28 UTC, merged