Fix namespace issue
belvo-finance/belvo-ruby pull request #132
Opened 2022-07-25 23:36 UTC by juanmex

:question: What
---

:speech_balloon: Why
---

2022-07-25 23:53 UTC, juanmex commented on lib/belvo/utils.rb
> +
Fixed in d7cae96995329e0876cf42da897bb9dc7197db47

2022-07-25 23:53 UTC, juanmex commented on lib/belvo/utils.rb
> +  class Utils
Fixed in d7cae96995329e0876cf42da897bb9dc7197db47

2022-07-26 19:31 UTC, blv-dianaenriquez commented
Hey @juanmex, 
Gracias for your contribution! We appreciate you taking the time to create this PR to fix a missed bug. 🤟 

One required step for merging this branch with the master branch is passing all the unit tests. For your PR, we identified an error related to the `spec/belvo/utils_spec.rb` file as it seems not to be updated when other changes were made. 
![image](https://user-images.githubusercontent.com/108693790/181094782-76db9b27-62f6-429b-aa2b-b87065fafba0.png)

Do you mind updating the test to move this forward?

2022-07-26 19:33 UTC, blv-dianaenriquez requested changes
Waiting for `utils_spec.rb` to be fixed.

2022-07-26 19:56 UTC, juanmex commented
> Waiting for `utils_spec.rb` to be fixed.

Fixed in 3f2d647e7cf0c47ee5c0d21ada022137b8599bbe

2022-07-28 14:19 UTC, blv-dianaenriquez approved these changes
Thank you 👍🏼

2022-07-28 14:31 UTC, uli-belvo approved these changes
Thanks for your contribution.

2023-03-08 14:18 UTC, closed without merging