Requi9re link param for transaction list endpoint
belvo-finance/belvo-ruby pull request #137
Opened 2022-09-01 15:34 UTC by blv-geoffreyvandercruyssen

:question: What
---

Make link parameter mandatory for transactions link parameter

:speech_balloon: Why
---

To sync the SDK with public_api

 
https://belvoteam.atlassian.net/browse/BEL-14880

2022-09-01 16:44 UTC, blv-beni commented on lib/belvo/http.rb
> +      $stdout.puts response.inspect
Is this a leftover?

2022-09-01 17:23 UTC, blv-geoffreyvandercruyssen commented on lib/belvo/http.rb
> +      $stdout.puts response.inspect
I left it here so you can see the response in the test container. Will remove it once I fix this issue.

2022-09-07 16:09 UTC, blv-luisguerrero commented on lib/belvo/resources.rb
> +      @session.list(@endpoint, params: params)
Hey, @blv-geoffreyvandercruyssen – I understand that the problem is in the tests failing because the new tests are returning a `nil` response instead of the expected `{}`. Although I’ve used another tests library, these ones look right to me.
My doubt is: are you calling `@session.list(...` instead of the get function above because the latter is not working?

2022-09-07 16:14 UTC, blv-geoffreyvandercruyssen commented on lib/belvo/resources.rb
> +      @session.list(@endpoint, params: params)
Basically I am overwriting the `list` method from Resource to force the `link` parameter. I am doing the exact same call as that method, just with some magic before that (just forcing the link)

2022-09-07 16:14 UTC, blv-geoffreyvandercruyssen commented on lib/belvo/resources.rb
> +      @session.list(@endpoint, params: params)
```    
def list(params: nil)
  @session.list(@endpoint, params: params)
end```

2022-09-07 19:50 UTC, blv-luisguerrero requested changes
Hey, @blv-geoffreyvandercruyssen – I included some format suggestions to the tests, according to the overall implementation for GET calls in this project.

Now the tests within the `transaction_spec.rb` file execute with success.

2022-09-07 19:50 UTC, blv-luisguerrero commented on lib/belvo/resources.rb
> +      @session.list(@endpoint, params: params)
@blv-geoffreyvandercruyssen I tested the code and it seems that tests are failing due to a format issue. I'll add the suggestions in the code below.

2022-09-07 19:50 UTC, blv-luisguerrero commented on spec/belvo/transaction_spec.rb
```suggestion
  def mock_list_with_link
    mock_login_ok
    WebMock.stub_request(:get, 'http://fake.api/api/transactions/').with(
      basic_auth: %w[foo bar],
      query: { link: 'some-link-uuid' }
    ).to_return(
      status: 200,
      body: {
        count: 1,
        next: nil,
        previous: nil,
        results: [transaction_resp.transform_keys(&:to_s)]
      }.to_json
    )
  end
```

2022-09-07 19:50 UTC, blv-luisguerrero commented on spec/belvo/transaction_spec.rb
> +  def mock_list_with_link_with_params
```suggestion
  def mock_list_with_link_with_params
    mock_login_ok
    WebMock.stub_request(:get, 'http://fake.api/api/transactions/').with(
      basic_auth: %w[foo bar],
      query: { foo: 0, link: 'some-link-uuid' }
    ).to_return(
      status: 200,
      body: {
        count: 1,
        next: nil,
        previous: nil,
        results: [transaction_resp.transform_keys(&:to_s)]
      }.to_json
    )
  end
```

2022-09-07 19:50 UTC, blv-luisguerrero commented on spec/belvo/transaction_spec.rb
> +    ).to eq(transaction_resp)
```suggestion
    ).to eq([transaction_resp.transform_keys(&:to_s)])
```

2022-09-07 19:50 UTC, blv-luisguerrero commented on spec/belvo/transaction_spec.rb
> +    ).to eq(transaction_resp)
```suggestion
    ).to eq([transaction_resp.transform_keys(&:to_s)])
```

2022-09-22 13:13 UTC, blv-luisguerrero approved these changes

2022-09-23 08:11 UTC, blv-albertmaristany commented on lib/belvo/resources.rb
> +    def list(id:, params: nil)
Will this break our customer integrations?
If they are already using:
```
client.transactions.list
```
and being `id` required now, will this :point_up: fail?

Also, `id` is a bit ambiguous, should it be `link_id`?

2022-09-23 11:28 UTC, blv-geoffreyvandercruyssen commented on lib/belvo/resources.rb
> +    def list(id:, params: nil)
Good spot, improved

2022-09-23 12:57 UTC, blv-albertmaristany approved these changes

2022-09-28 10:05 UTC, merged