Add allow requesting link tokens
belvo-finance/belvo-ruby pull request #41
Opened 2020-10-02 23:22 UTC by shekodn

:question: What
---
Added new method to allow users to get a token for a link with an specific scope

:speech_balloon: Why
---
We will start using tokens' scope by limiting their range of action to specific links

2020-10-05 07:24 UTC, menecio requested changes

2020-10-05 07:24 UTC, menecio commented on lib/belvo/http.rb
> +    end
There is no need for this method, you are adding 8 LoC just to encapsulate a `@session.post()` call and ending up duplicating the `raise_for_status`

2020-10-05 07:24 UTC, menecio commented on lib/belvo/resources.rb
> +    # @return [Hash] with a "refresh" and "access" token
If we start returning hashes here, we should start doing it all over. I recommend to have this one as the rest and fix all responses in a separated PR

2020-10-05 21:02 UTC, shekodn commented on lib/belvo/http.rb
> +    end
Hey @menecio , 

I was doing a mistake. When I was doing `response = @session.post(path, data.to_json)` I was getting the following.

```
400
[{"field"=>"institution", "request_id"=>"0492a81a41d73c6a6eb491c5724b2caf", "message"=>"This field is required.", "code"=>"required"}, {"field"=>"username", "request_id"=>"0492a81a41d73c6a6eb491c5724b2caf", "message"=>"This field is required.", "code"=>"required"}, {"field"=>"password", "request_id"=>"0492a81a41d73c6a6eb491c5724b2caf", "message"=>"This field is required.", "code"=>"required"}]
```

Then I noticed I was using _path_, instead of _resource_path_.

Using `response = @session.post(resource_path, data.to_json)` did the trick. Thanks.

2020-10-05 21:17 UTC, shekodn commented on lib/belvo/resources.rb
> +    # @return [Hash] with a "refresh" and "access" token
Sorry @menecio , I didn’t catch that. As far as I know, we have been returning hashes before. For example:

```
require 'belvo'

belvo = Belvo::Client.new(
  'xxx,
  'xxx',
  'https://api.belvo.co'
)

test_link = 'a-link'

begin

    detail = belvo.links.detail(id: test_link)
    puts detail.class
    puts detail

    token = belvo.links.token(id: test_link, scopes: "read_links")
    puts token.class
    puts token
    
  rescue Belvo::RequestError => e
    puts e.status_code
    puts e.detail
end
```

Both return values are hashes (detail and token):
```
Hash
{"id"=>"234531f9-6157-4e4c-be84-002194c1a4fb", "institution"=>"bancoazteca_mx_retail", "access_mode"=>"single", "last_accessed_at"=>"2020-08-25T21:55:51.860926Z", "status"=>"valid", "created_by"=>"57c15387-f10d-4afa-b32a-d70dbdce15d6"}

Hash
{"refresh"=>"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9", "access"=>"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9"}

```

2020-10-06 14:29 UTC, menecio approved these changes

2020-10-07 19:54 UTC, Janee commented on lib/belvo/resources.rb
> +    # @return [Hash] with a "refresh" and "access" token
@menecio the SDK returns hash objects but not hash symbols (best practice), I don't see any issue with this.

However, we can maybe add the `symbolized_keys` method to the gem?
https://apidock.com/rails/Hash/symbolize_keys

2020-10-07 19:55 UTC, Janee approved these changes

2020-10-07 20:29 UTC, merged